// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DataAccess.Models
{
    public partial class Employee
    {
        public Employee()
        {
            JobDetail = new HashSet<JobDetail>();
            LeaveRequests = new HashSet<LeaveRequests>();
        }

        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public int DepartmentId { get; set; }
        public int DesignationId { get; set; }
        public DateTime Dob { get; set; }
        public string AboutMe { get; set; }
        public string Gender { get; set; }
        public string Address { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime? ModifiedDate { get; set; }

        public virtual Department Department { get; set; }
        public virtual Designation Designation { get; set; }
        public virtual ICollection<JobDetail> JobDetail { get; set; }
        public virtual ICollection<LeaveRequests> LeaveRequests { get; set; }
    }
}