// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DataAccess.Models
{
    public partial class JobDetail
    {
        public int Id { get; set; }
        public int EmployeeId { get; set; }
        public DateTime JoiningDate { get; set; }
        public DateTime? ReleavingDate { get; set; }
        public int LeavesAllocated { get; set; }
        public int? ReportingTo { get; set; }
        public string EmailAlertTo { get; set; }
        public string PreviousCompany { get; set; }
        public int? PreviousExp { get; set; }
        public bool? IsActive { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime? ModifiedDate { get; set; }

        public virtual Employee Employee { get; set; }
    }
}