// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DataAccess.Models
{
    public partial class LeaveType
    {
        public LeaveType()
        {
            LeaveRequests = new HashSet<LeaveRequests>();
        }

        public int LeaveTypeId { get; set; }
        public string Name { get; set; }
        public string DisplayName { get; set; }
        public bool? IsActive { get; set; }

        public virtual ICollection<LeaveRequests> LeaveRequests { get; set; }
    }
}