// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DataAccess.Models
{
    public partial class UserNotification
    {
        public int Id { get; set; }
        public int EmployeeId { get; set; }
        public string Message { get; set; }
        public string RawData { get; set; }
        public DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
    }
}